package model;

// Generated 2015-1-11 20:25:15 by Hibernate Tools 3.4.0.CR1

/**
 * Friend generated by hbm2java
 */
public class Friend implements java.io.Serializable {

	private Integer fid;
	private String friendId;
	private String whos;
	private Integer newMessage;
	private Boolean isOnline;

	public Friend() {
	}

	public Friend(String friendId, String whos, Integer newMessage,
			Boolean isOnline) {
		this.friendId = friendId;
		this.whos = whos;
		this.newMessage = newMessage;
		this.isOnline = isOnline;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public String getFriendId() {
		return this.friendId;
	}

	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}

	public String getWhos() {
		return this.whos;
	}

	public void setWhos(String whos) {
		this.whos = whos;
	}

	public Integer getNewMessage() {
		return this.newMessage;
	}

	public void setNewMessage(Integer newMessage) {
		this.newMessage = newMessage;
	}

	public Boolean getIsOnline() {
		return this.isOnline;
	}

	public void setIsOnline(Boolean isOnline) {
		this.isOnline = isOnline;
	}

}
