package model;

// Generated 2015-1-10 22:02:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userId;
	private String userPwd;
	private Boolean isOnline;
	private Date registerDate;
	private String recentLoginIp;
	private Integer recentLoginPort;
	private Date recentLogoutDate;
	private Boolean hasNewMessage;

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}

	public User(String userId, String userPwd, Boolean isOnline,
			Date registerDate, String recentLoginIp, Integer recentLoginPort,
			Date recentLogoutDate, Boolean hasNewMessage) {
		this.userId = userId;
		this.userPwd = userPwd;
		this.isOnline = isOnline;
		this.registerDate = registerDate;
		this.recentLoginIp = recentLoginIp;
		this.recentLoginPort = recentLoginPort;
		this.recentLogoutDate = recentLogoutDate;
		this.hasNewMessage = hasNewMessage;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public Boolean getIsOnline() {
		return this.isOnline;
	}

	public void setIsOnline(Boolean isOnline) {
		this.isOnline = isOnline;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public String getRecentLoginIp() {
		return this.recentLoginIp;
	}

	public void setRecentLoginIp(String recentLoginIp) {
		this.recentLoginIp = recentLoginIp;
	}

	public Integer getRecentLoginPort() {
		return this.recentLoginPort;
	}

	public void setRecentLoginPort(Integer recentLoginPort) {
		this.recentLoginPort = recentLoginPort;
	}

	public Date getRecentLogoutDate() {
		return this.recentLogoutDate;
	}

	public void setRecentLogoutDate(Date recentLogoutDate) {
		this.recentLogoutDate = recentLogoutDate;
	}

	public Boolean getHasNewMessage() {
		return this.hasNewMessage;
	}

	public void setHasNewMessage(Boolean hasNewMessage) {
		this.hasNewMessage = hasNewMessage;
	}

}
